In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('9810022501_databaseLoadingData.csv')

In [7]:
df.head()

,REF_DATE,GEO,DGUID,Age (13B),Knowledge of official languages (5),Statistics (2),UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2021,Canada,2021A000011124,Total - Age,Total - Knowledge of official languages,2021 Counts,NaN,0,units,0,NaN,1.1.1.1,36620955,NaN,NaN,NaN,0
1,2021,Canada,2021A000011124,Total - Age,English only,2021 Counts,NaN,0,units,0,NaN,1.1.2.1,25261655,NaN,NaN,NaN,0
2,2021,Canada,2021A000011124,Total - Age,French only,2021 Counts,NaN,0,units,0,NaN,1.1.3.1,4087895,NaN,NaN,NaN,0
3,2021,Canada,2021A000011124,Total - Age,English and French,2021 Counts,NaN,0,units,0,NaN,1.1.4.1,6581680,NaN,NaN,NaN,0
4,2021,Canada,2021A000011124,Total - Age,Neither English nor French,2021 Counts,NaN,0,units,0,NaN,1.1.5.1,689730,NaN,NaN,NaN,0

In [8]:
df.shape

(3433, 17)

In [9]:
df.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Age (13B)',
       'Knowledge of official languages (5)', 'Statistics (2)', 'UOM',
       'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE',
       'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='str')

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3433 entries, 0 to 3432
Data columns (total 17 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   REF_DATE                             3433 non-null   int64
 1   GEO                                  3433 non-null   str
 2   DGUID                                3433 non-null   str
 3   Age (13B)                            3433 non-null   str
 4   Knowledge of official languages (5)  3433 non-null   str
 5   Statistics (2)                       3433 non-null   str
 6   UOM                                  0 non-null      float64
 7   UOM_ID                               3433 non-null   int64
 8   SCALAR_FACTOR                        3433 non-null   str
 9   SCALAR_ID                            3433 non-null   int64
 10  VECTOR                               0 non-null      float64
 11  COORDINATE                           3433 non-null   str
 12  VALUE                                3433 non-null   int64
 13  STATUS                               0 non-null      float64
 14  SYMBOL                               0 non-null      float64
 15  TERMINATED                           0 non-null      float64
 16  DECIMALS                             3433 non-null   int64
dtypes: float64(5), int64(5), str(7)
memory usage: 456.1 KB

In [11]:
df.describe()

,REF_DATE,UOM,UOM_ID,SCALAR_ID,VECTOR,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
count,3433.0,0.0,3433.0,3433.0,0.0,3.433000e+03,0.0,0.0,0.0,3433.0
mean,2021.0,NaN,0.0,0.0,NaN,4.033769e+04,NaN,NaN,NaN,0.0
std,0.0,NaN,0.0,0.0,NaN,7.761676e+05,NaN,NaN,NaN,0.0
min,2021.0,NaN,0.0,0.0,NaN,5.000000e+00,NaN,NaN,NaN,0.0
25%,2021.0,NaN,0.0,0.0,NaN,1.000000e+02,NaN,NaN,NaN,0.0
50%,2021.0,NaN,0.0,0.0,NaN,3.235000e+03,NaN,NaN,NaN,0.0
75%,2021.0,NaN,0.0,0.0,NaN,1.036000e+04,NaN,NaN,NaN,0.0
max,2021.0,NaN,0.0,0.0,NaN,3.662096e+07,NaN,NaN,NaN,0.0

In [17]:
df[['REF_DATE', 'GEO', 'DGUID', 'VALUE']].head()

   REF_DATE     GEO           DGUID     VALUE
0      2021  Canada  2021A000011124  36620955
1      2021  Canada  2021A000011124  25261655
2      2021  Canada  2021A000011124   4087895
3      2021  Canada  2021A000011124   6581680
4      2021  Canada  2021A000011124    689730

In [13]:
df.duplicated()
df_clean = df.drop_duplicates()

In [28]:
df[['REF_DATE', 'GEO', 'DGUID', 'VALUE']].sort_values(by='VALUE', ascending=True).to_csv('LANGUAGES.csv', index=False)