In [41]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('PDCount.csv')
# PDCount.csv is renamed csv file from https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=9810000201
# Used download option CSV 'download selected data (for database loading)'
df.to_csv('PDCount.csv', index=False)
df = pd.read_csv('PDCount.csv')
df.head(15)

,REF_DATE,GEO,DGUID,Population and dwelling counts (13),UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,2021,Canada,2021A000011124,"Population, 2021",NaN,0,units,0,NaN,1.10,36991981.0,NaN,NaN,NaN,0
1,2021,Canada,2021A000011124,"Population, 2016",NaN,0,units,0,NaN,1.20,35151728.0,NaN,NaN,NaN,0
2,2021,Canada,2021A000011124,"Population percentage change, 2016 to 2021",NaN,0,units,0,NaN,1.30,5.2,NaN,NaN,NaN,1
3,2021,Canada,2021A000011124,"Total private dwellings, 2021",NaN,0,units,0,NaN,1.40,16284235.0,NaN,NaN,NaN,0
4,2021,Canada,2021A000011124,"Total private dwellings, 2016",NaN,0,units,0,NaN,1.50,15412443.0,NaN,NaN,NaN,0
5,2021,Canada,2021A000011124,"Total private dwellings percentage change, 201...",NaN,0,units,0,NaN,1.60,5.7,NaN,NaN,NaN,1
6,2021,Canada,2021A000011124,"Private dwellings occupied by usual residents,...",NaN,0,units,0,NaN,1.70,14978941.0,NaN,NaN,NaN,0
7,2021,Canada,2021A000011124,"Private dwellings occupied by usual residents,...",NaN,0,units,0,NaN,1.80,14072079.0,NaN,NaN,NaN,0
8,2021,Canada,2021A000011124,Private dwellings occupied by usual residents ...,NaN,0,units,0,NaN,1.90,6.4,NaN,NaN,NaN,1
9,2021,Canada,2021A000011124,"Land area in square kilometres, 2021",NaN,0,units,0,NaN,1.10,8788702.8,NaN,NaN,NaN,2
10,2021,Canada,2021A000011124,"Population density per square kilometre, 2021",NaN,0,units,0,NaN,1.11,4.2,NaN,NaN,NaN,1
11,2021,Canada,2021A000011124,"National population rank, 2021",NaN,0,units,0,NaN,1.12,NaN,...,NaN,NaN,0
12,2021,Canada,2021A000011124,"Province/territory population rank, 2021",NaN,0,units,0,NaN,1.13,NaN,...,NaN,NaN,0
13,2021,Admirals Beach,2021A00051001186,"Population, 2021",NaN,0,units,0,NaN,4.10,97.0,NaN,NaN,NaN,0
14,2021,Admirals Beach,2021A00051001186,"Population, 2016",NaN,0,units,0,NaN,4.20,135.0,NaN,NaN,NaN,0

In [ ]:
print(df.shape)
print(df.columns)
#understanding the layout of the CSV

(67106, 15)
Index(['REF_DATE', 'GEO', 'DGUID', 'Population and dwelling counts (13)',
       'UOM', 'UOM_ID', 'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE',
       'VALUE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='str')

In [ ]:
print(df.info())
#understanding the layout of the CSV

<class 'pandas.DataFrame'>
RangeIndex: 67106 entries, 0 to 67105
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   REF_DATE                             67106 non-null  int64
 1   GEO                                  67106 non-null  str
 2   DGUID                                67106 non-null  str
 3   Population and dwelling counts (13)  67106 non-null  str
 4   UOM                                  0 non-null      float64
 5   UOM_ID                               67106 non-null  int64
 6   SCALAR_FACTOR                        67106 non-null  str
 7   SCALAR_ID                            67106 non-null  int64
 8   VECTOR                               0 non-null      float64
 9   COORDINATE                           67106 non-null  float64
 10  VALUE                                65785 non-null  float64
 11  STATUS                               1360 non-null   str
 12  SYMBOL                               1814 non-null   str
 13  TERMINATED                           0 non-null      float64
 14  DECIMALS                             67106 non-null  int64
dtypes: float64(5), int64(4), str(6)
memory usage: 7.7 MB
None

In [ ]:
df['SCALAR_ID']
#understanding the layout of the CSV

0        0
1        0
2        0
3        0
4        0
        ..
67101    0
67102    0
67103    0
67104    0
67105    0
Name: SCALAR_ID, Length: 67106, dtype: int64

In [ ]:
print(df.describe())
#understanding the layout of the CSV

       REF_DATE  UOM   UOM_ID  SCALAR_ID  VECTOR    COORDINATE         VALUE  \
count   67106.0  0.0  67106.0    67106.0     0.0  67106.000000  6.578500e+04
mean     2021.0  NaN      0.0        0.0     NaN   2751.271504  4.545769e+03
std         0.0  NaN      0.0        0.0     NaN   1581.096991  2.358593e+05
min      2021.0  NaN      0.0        0.0     NaN      1.100000 -1.000000e+02
25%      2021.0  NaN      0.0        0.0     NaN   1380.325000  7.300000e+00
50%      2021.0  NaN      0.0        0.0     NaN   2775.000000  1.570000e+02
75%      2021.0  NaN      0.0        0.0     NaN   4115.275000  8.100000e+02
max      2021.0  NaN      0.0        0.0     NaN   5468.900000  3.699198e+07

       TERMINATED      DECIMALS
count         0.0  67106.000000
mean          NaN      0.461538
std           NaN      0.634329
min           NaN      0.000000
25%           NaN      0.000000
50%           NaN      0.000000
75%           NaN      1.000000
max           NaN      2.000000

In [ ]:
df = df[['GEO', 'DGUID', 'Population and dwelling counts (13)', 'VALUE']]
df.head(13)
#understanding the filtered layout of the CSV

,GEO,DGUID,Population and dwelling counts (13),VALUE
0,Canada,2021A000011124,"Population, 2021",36991981.0
1,Canada,2021A000011124,"Population, 2016",35151728.0
2,Canada,2021A000011124,"Population percentage change, 2016 to 2021",5.2
3,Canada,2021A000011124,"Total private dwellings, 2021",16284235.0
4,Canada,2021A000011124,"Total private dwellings, 2016",15412443.0
5,Canada,2021A000011124,"Total private dwellings percentage change, 201...",5.7
6,Canada,2021A000011124,"Private dwellings occupied by usual residents,...",14978941.0
7,Canada,2021A000011124,"Private dwellings occupied by usual residents,...",14072079.0
8,Canada,2021A000011124,Private dwellings occupied by usual residents ...,6.4
9,Canada,2021A000011124,"Land area in square kilometres, 2021",8788702.8
10,Canada,2021A000011124,"Population density per square kilometre, 2021",4.2
11,Canada,2021A000011124,"National population rank, 2021",NaN
12,Canada,2021A000011124,"Province/territory population rank, 2021",NaN

In [ ]:
df.to_csv('ProcessedPopDwelCountMNK.csv', index=False)
#Creation of the preocessed CSV

NameError: name 'df' is not defined